// <auto-generated />
using System;
using Common.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Data.Migrations
{
    [DbContext(typeof(EFHospitalDbContext))]
    [Migration("20260507112046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERManagementSystem.Models.ER_Room", b =>
                {
                    b.Property<int>("Room_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Room_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Room_ID"));

                    b.Property<string>("Availability_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Availability_Status");

                    b.Property<int?>("Current_Visit_ID")
                        .HasColumnType("int")
                        .HasColumnName("Current_Visit_ID");

                    b.Property<string>("Room_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Room_Type");

                    b.HasKey("Room_ID");

                    b.ToTable("ER_Room", (string)null);
                });

            modelBuilder.Entity("ERManagementSystem.Models.ER_Visit", b =>
                {
                    b.Property<int>("Visit_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Visit_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Visit_ID"));

                    b.Property<DateTime>("Arrival_date_time")
                        .HasColumnType("datetime2")
                        .HasColumnName("Arrival_date_time");

                    b.Property<string>("Chief_Complaint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Chief_Complaint");

                    b.Property<string>("Patient_ID")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("Patient_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Status");

                    b.HasKey("Visit_ID");

                    b.ToTable("ER_Visit", (string)null);
                });

            modelBuilder.Entity("ERManagementSystem.Models.Examination", b =>
                {
                    b.Property<int>("Exam_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Exam_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Exam_ID"));

                    b.Property<int>("Doctor_ID")
                        .HasColumnType("int")
                        .HasColumnName("Doctor_ID");

                    b.Property<DateTime>("Exam_Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("Exam_Time");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Notes");

                    b.Property<int>("Room_ID")
                        .HasColumnType("int")
                        .HasColumnName("Room_ID");

                    b.Property<int>("Visit_ID")
                        .HasColumnType("int")
                        .HasColumnName("Visit_ID");

                    b.HasKey("Exam_ID");

                    b.ToTable("Examination", (string)null);
                });

            modelBuilder.Entity("ERManagementSystem.Models.Transfer_Log", b =>
                {
                    b.Property<int>("Transfer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Transfer_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Transfer_ID"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FilePath");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Status");

                    b.Property<string>("Target_System")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Target_System");

                    b.Property<DateTime>("Transfer_Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("Transfer_Time");

                    b.Property<int>("Visit_ID")
                        .HasColumnType("int")
                        .HasColumnName("Visit_ID");

                    b.HasKey("Transfer_ID");

                    b.ToTable("Transfer_Log", (string)null);
                });

            modelBuilder.Entity("ERManagementSystem.Models.Triage", b =>
                {
                    b.Property<int>("Triage_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Triage_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Triage_ID"));

                    b.Property<int>("Nurse_ID")
                        .HasColumnType("int")
                        .HasColumnName("Nurse_ID");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Specialization");

                    b.Property<int>("Triage_Level")
                        .HasColumnType("int")
                        .HasColumnName("Triage_Level");

                    b.Property<DateTime>("Triage_Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("Triage_Time");

                    b.Property<int>("Visit_ID")
                        .HasColumnType("int")
                        .HasColumnName("Visit_ID");

                    b.HasKey("Triage_ID");

                    b.ToTable("Triage", (string)null);
                });

            modelBuilder.Entity("ERManagementSystem.Models.Triage_Parameters", b =>
                {
                    b.Property<int>("Triage_ID")
                        .HasColumnType("int")
                        .HasColumnName("Triage_ID");

                    b.Property<int>("Bleeding")
                        .HasColumnType("int")
                        .HasColumnName("Bleeding");

                    b.Property<int>("Breathing")
                        .HasColumnType("int")
                        .HasColumnName("Breathing");

                    b.Property<int>("Consciousness")
                        .HasColumnType("int")
                        .HasColumnName("Consciousness");

                    b.Property<int>("Injury_Type")
                        .HasColumnType("int")
                        .HasColumnName("Injury_Type");

                    b.Property<int>("Pain_Level")
                        .HasColumnType("int")
                        .HasColumnName("Pain_Level");

                    b.HasKey("Triage_ID");

                    b.ToTable("Triage_Parameters", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AllergyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllergyCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AllergyCategory");

                    b.Property<string>("AllergyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AllergyName");

                    b.Property<string>("AllergyType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AllergyType");

                    b.HasKey("Id");

                    b.ToTable("Allergy", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.MedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BloodType");

                    b.Property<string>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ChronicConditions");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Rh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RH");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalHistory", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BasePrice");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ConsultationDate");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Diagnosis");

                    b.Property<int?>("DiscountApplied")
                        .HasColumnType("int")
                        .HasColumnName("DiscountApplied");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FinalPrice");

                    b.Property<int>("HistoryId")
                        .HasColumnType("int")
                        .HasColumnName("HistoryID");

                    b.Property<bool>("PoliceNotified")
                        .HasColumnType("bit")
                        .HasColumnName("PoliceNotified");

                    b.Property<int>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("SourceID");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SourceType");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Symptoms");

                    b.Property<int?>("TransplantId")
                        .HasColumnType("int")
                        .HasColumnName("TransplantID");

                    b.HasKey("Id");

                    b.HasIndex("HistoryId");

                    b.ToTable("MedicalRecord", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnp")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("CNP");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime?>("Dod")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfDeath");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EmergencyContact");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("Archived");

                    b.Property<bool>("IsDonor")
                        .HasColumnType("bit")
                        .HasColumnName("IsDonor");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sex");

                    b.Property<bool>("Transferred")
                        .HasColumnType("bit")
                        .HasColumnName("Transferred");

                    b.HasKey("Id");

                    b.HasIndex("Cnp")
                        .IsUnique();

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.PatientAllergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .HasColumnType("int")
                        .HasColumnName("AllergyID");

                    b.Property<int>("MedicalHistoryId")
                        .HasColumnType("int")
                        .HasColumnName("HistoryID");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SeverityLevel");

                    b.HasKey("AllergyId", "MedicalHistoryId");

                    b.HasIndex("MedicalHistoryId");

                    b.ToTable("PatientAllergies", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<string>("DoctorNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DoctorNotes");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    b.HasKey("Id");

                    b.HasIndex("RecordId")
                        .IsUnique();

                    b.ToTable("Prescription", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.PrescriptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrescrItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("MedName");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID");

                    b.Property<string>("Quantity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Transplant", b =>
                {
                    b.Property<int>("TransplantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransplantID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransplantId"));

                    b.Property<float>("CompatibilityScore")
                        .HasColumnType("real")
                        .HasColumnName("CompatibilityScore");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int")
                        .HasColumnName("DonorID");

                    b.Property<string>("OrganType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("OrganType");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("ReceiverID");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("RequestDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("TransplantDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("TransplantDate");

                    b.HasKey("TransplantId");

                    b.ToTable("Transplants", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.MedicalHistory", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Patient", "Patient")
                        .WithOne("MedicalHistory")
                        .HasForeignKey("HospitalManagement.Entity.MedicalHistory", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagement.Entity.MedicalRecord", b =>
                {
                    b.HasOne("HospitalManagement.Entity.MedicalHistory", "History")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("History");
                });

            modelBuilder.Entity("HospitalManagement.Entity.PatientAllergy", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Allergy", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Entity.MedicalHistory", "MedicalHistory")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("MedicalHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("MedicalHistory");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Prescription", b =>
                {
                    b.HasOne("HospitalManagement.Entity.MedicalRecord", "MedicalRecord")
                        .WithOne("Prescription")
                        .HasForeignKey("HospitalManagement.Entity.Prescription", "RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("HospitalManagement.Entity.PrescriptionItem", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Prescription", "Prescription")
                        .WithMany("MedicationList")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalManagement.Entity.MedicalHistory", b =>
                {
                    b.Navigation("MedicalRecords");

                    b.Navigation("PatientAllergies");
                });

            modelBuilder.Entity("HospitalManagement.Entity.MedicalRecord", b =>
                {
                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Patient", b =>
                {
                    b.Navigation("MedicalHistory");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Prescription", b =>
                {
                    b.Navigation("MedicationList");
                });
#pragma warning restore 612, 618
        }
    }
}
